/**
 * ActionTypes for Actions & Reducer.
 */
export const SET_USER_REPOSITORIES = 'REPOSITORY.USER_RESPOSITORIES';
export const SET_USER_REPOSITORIES_ERROR_MESSAGE = "REPOSITORY.USER_REPO_ERROR_MESSAGE";
export const SET_REPOSITORY_COMMITS = 'REPOSITORY.COMMITS';